# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Aayli/Desktop/rgb2ycbcr/SR_6/SR_6.srcs/sources_1/ip/add_16x16/add_16x16.xci
# IP: The module: 'add_16x16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Aayli/Desktop/rgb2ycbcr/SR_6/SR_6.srcs/sources_1/ip/add_16x16/add_16x16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'add_16x16'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Aayli/Desktop/rgb2ycbcr/SR_6/SR_6.srcs/sources_1/ip/add_16x16/add_16x16.xci
# IP: The module: 'add_16x16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Aayli/Desktop/rgb2ycbcr/SR_6/SR_6.srcs/sources_1/ip/add_16x16/add_16x16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'add_16x16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
